### Site Settings ###
title               : neel_code
description         : >-
                      "Caffeine :coffee: powered coding,
                      adapting to TDD and learning to handle to data."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : sabya14/sabya14     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/projects.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Sabyasachi Nandy
#  behance           : your_username
# dribbble          : your_username
  email             : sabya.nandy14@gmail.com
#  facebook          : your_username
  github            : sabya14
# gitlab            : your_username
# instagram         : your_username
  linkedin          : sabyasachi-nandy-293574132
  medium            : sabya.nandy14
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
#collections:
#  projects:
#    output: true
#    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
